### PR TITLE
COMMIT TEST

### PR DESCRIPTION
**Pull request by AAS1214**

### CODE REVIEW

**Comment by AAS1214** [comment]
ADMN FILE

**Review by httprenz — CHANGES_REQUESTED** [review]
ano yan bobo kaba ?

**Comment by AAS1214** [comment]
Added new database file (examwebsite-db.sql), deleted unnecessary files

**Comment by AAS1214** [comment]
Condition for user pics

**Review by httprenz — APPROVED** [review]

**Review by httprenz — APPROVED** [review]

**Pull request merged**
